auto: true
server: true
pygments: true
permalink: none
exclude:
- .gitignore
- README.md
prose:
  rooturl: "_posts"
  metadata:
    "_posts/shows": |
      layout: "show"
      city: "NYC"
      venue: "Pianos"
      show_date: "May 25"
      link: "http://www.google.com"