auto: true
server: true
pygments: true
permalink: none
future: true
past: false
exclude:
- .gitignore
- README.md
prose:
  metadata:
    "_posts/shows": |
      layout: show
      city: CITY NAME
      venue: VENUE NAME
      show_date: DATE
      link: http://www.google.com